!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  auto_exposure_priority: true
  backlight_compensation: false
  brightness: -23
  contrast: 64
  enable_auto_exposure: true
  enable_auto_white_balance: true
  exposure: 166
  frames_queue_size: 16
  gain: 64
  gamma: 300
  global_time_enabled: true
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      auto_exposure_priority: true
      backlight_compensation: false
      brightness: -23
      contrast: 64
      enable_auto_exposure: true
      enable_auto_white_balance: true
      exposure: 166
      frames_queue_size: 16
      gain: 64
      gamma: 300
      global_time_enabled: true
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      hue: 0
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      power_line_frequency: 3
      saturation: 97
      sharpness: 69
      state: true
      type: ''
      white_balance: 5809.0
    state: []
  hue: 0
  power_line_frequency: 3
  saturation: 97
  sharpness: 69
  white_balance: 5809.0
state: []
