#documentation : http://wiki.ros.org/navigation/Tutorials/RobotSetup

obstacle_range: 6.0 # only detect obstacles within obstacle_range meters
raytrace_range: 3.0 # robot will attempt to clear out space in front of it up to raytrace_range meters away given a sensor reading
footprint: [[0.4937, 0.28545], [0.4937, -0.28545], [-0.4937, -0.28545], [-0.4937, 0.28545]]

#robot_radius: ir_of_robot
inflation_radius: 0.5 # stay inflation_radius meters away from obstacles

observation_sources: realsense velodyne lane

realsense: {sensor_frame: frontCamera_link, data_type: PointCloud2, topic: /realsense/frontCamera/depth/points, marking: true, clearing: true}

velodyne: {sensor_frame: velodyne, data_type: PointCloud2, topic: /velodyne_points, marking: true, clearing: true}