# documentation : http://wiki.ros.org/navigation/Tutorials/RobotSetup

obstacle_range: 2.5 # only detect obstacles within obstacle_range meters
raytrace_range: 3.0 # robot will attempt to clear out space in front of it up to raytrace_range meters away given a sensor reading

### Keep commented if using robot radius
# footprint: [[0.4937, 0.28545], [0.4937, -0.28545], [-0.4937, -0.28545], [-0.4937, 0.28545]]
# footprint_padding: 0

robot_radius: 0.6

inflation: # Name of the inflation layer plugin in global costmap params
  # Inflation radius = Robot_radius + difference
  inflation_radius: 0.7
  cost_scaling_factor: 1.0

observation_sources: realsense velodyne

realsense: {sensor_frame: frontCamera_link, data_type: PointCloud2, topic: /frontCamera/depth/color/points, marking: true, clearing: true}

velodyne: {sensor_frame: velodyne, data_type: PointCloud2, topic: /velodyne_points, marking: true, clearing: true}