global_costmap:
  plugins:
      - {name: lane, type: "costmap_2d::ObstacleLayer"}
  lane:
    observation_sources: fake_lane_sensor
    fake_lane_sensor: {data_type: PointCloud2, sensor_frame: frontCamera_color_optical_frame, clearing: true, marking: true, topic: /lane/pointCloud, observation_persistence: 0.5, expected_update_rate: 0.5}
  
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0 #  Hz
  publish_frequency: 2.0 # hz
  static_map: false # if true, map comes from external source
  rolling_window: true
  always_send_full_costmap: true # when false, updates get sent on costmap_updates topic
  width: 12.0
  height: 14.0
  resolution: 0.1
  map_type: costmap
  transform_tolerance: 1.5 # increased this
