global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0 #  Hz
  publish_frequency: 2.0 # hz
  static_map: false # if true, map comes from external source
  rolling_window: true # yes
  always_send_full_costmap: true # when false, updates get sent on costmap_updates topic
  width: 12.0
  height: 14.0
  resolution: 0.1 # def 0.05m
  map_type: costmap
  transform_tolerance: 1.5 # increased this

  # plugins:
  # #     # - {name: static_layer,   type: "costmap_2d::StaticLayer"}
  #     - {name: inflation,      type: "costmap_2d::InflationLayer"}

  # static_layer:
  #   map_topic: "/rtabmap/grid_map"
  #   first_map_only: false
